# Generated by Django 4.0.4 on 2022-05-31 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0002_contactsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='geeksmodel',
            name='arrival',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
